image: node:19

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g pnpm

install_dependencies:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - rm -rf public/*       # Clear the existing public directory
    - cp -r dist/* public/  # Copy the built files to the public directory
    #- echo "RewriteEngine On" >> public/.htaccess
    #- echo "RewriteCond %{REQUEST_FILENAME} !-f" >> public/.htaccess
    #- echo "RewriteCond %{REQUEST_FILENAME} !-d" >> public/.htaccess
    #- echo "RewriteRule . /index.html [L]" >> public/.htaccess
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master  # Change this to your default branch if it's not 'main'
