image: node:16

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g pnpm

install_dependencies:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - master

